# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cryptography.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import img
import back
import image
# import imagey


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1342, 766)
        Form.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(910, 10, 141, 41))
        self.frame_7.setMaximumSize(QtCore.QSize(500, 200))
        self.frame_7.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setGeometry(QtCore.QRect(0, 9, 911, 91))
        self.frame_8.setStyleSheet("background-color: rgb(171, 191, 255);\n"
"background-color: rgb(51, 51, 51);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 81, 81))
        self.frame_9.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 61))
        self.pushButton_4.setStyleSheet("background-color: rgb(51, 51, 51);\n"
"image: url(:/newPrefix/encrypt.jpg);")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.label = QtWidgets.QLabel(self.frame_8)
        self.label.setGeometry(QtCore.QRect(290, 20, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame_2.setStyleSheet("background-color: rgb(171, 191, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Form_2 = QtWidgets.QFrame(self.frame_2)
        self.Form_2.setMaximumSize(QtCore.QSize(16777215, 1500))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Form_2.setFont(font)
        self.Form_2.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.Form_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Form_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Form_2.setObjectName("Form_2")
        self.frame_4 = QtWidgets.QFrame(self.Form_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 100, 498))
        self.frame_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_4.setStyleSheet("\n"
"QFrame{\n"
"background-color: #000;\n"
"    background-color: rgb(99, 85, 58);\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"padding: 5px 10px;\n"
"border: none;\n"
"border-radius: 10px;\n"
"background: #000;\n"
"color: #fff;\n"
"}\n"
"\n"
"QPushButton: hover{\n"
"background-color: rgb(0,92,157);\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 26))
        self.pushButton_7.setMaximumSize(QtCore.QSize(78, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(99, 85, 58);\n"
"\n"
"image: url(:/newPrefix/houseY.png);")
        self.pushButton_7.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Downloads/icons8-home-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(99, 85, 58);\n"
"image: url(:/newPrefix/enter.png);\n"
"")
        self.pushButton_5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Downloads/icons8-login-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(99, 85, 58);\n"
"image: url(:/newPrefix/register.png);\n"
"")
        self.pushButton_6.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../Downloads/icons8-register-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.label_2 = QtWidgets.QLabel(self.Form_2)
        self.label_2.setGeometry(QtCore.QRect(200, 150, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Form_2)
        self.label_3.setGeometry(QtCore.QRect(280, 250, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Form_2)
        self.label_4.setGeometry(QtCore.QRect(120, 320, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.Form_2)
        self.lineEdit.setGeometry(QtCore.QRect(390, 80, 481, 131))
        self.lineEdit.setStyleSheet("background-color: rgb(179, 177, 150);\n"
"border-radius:12px;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Form_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(400, 240, 121, 41))
        self.lineEdit_2.setStyleSheet("background-color: rgb(179, 177, 150);\n"
"border-radius:12px;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Form_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(400, 300, 121, 41))
        self.lineEdit_3.setStyleSheet("background-color: rgb(179, 177, 150);\n"
"border-radius:12px;")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.SHOW = QtWidgets.QPushButton(self.Form_2)
        self.SHOW.setGeometry(QtCore.QRect(580, 280, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.SHOW.setFont(font)
        self.SHOW.setStyleSheet("border-radius:12px;\n"
"background-color: rgb(226, 186, 90);")
        self.SHOW.setObjectName("SHOW")
        self.RESET = QtWidgets.QPushButton(self.Form_2)
        self.RESET.setGeometry(QtCore.QRect(680, 280, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.RESET.setFont(font)
        self.RESET.setStyleSheet("border-radius:12px;\n"
"background-color: rgb(216, 150, 102);")
        self.RESET.setObjectName("RESET")
        self.EXIT = QtWidgets.QPushButton(self.Form_2)
        self.EXIT.setGeometry(QtCore.QRect(790, 280, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.EXIT.setFont(font)
        self.EXIT.setStyleSheet("border-radius:12px;\n"
"background-color: rgb(206, 69, 51);")
        self.EXIT.setObjectName("EXIT")
        self.horizontalLayout.addWidget(self.Form_2)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_6.setStyleSheet("background-color: rgb(51, 51, 68);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_3.setStyleSheet("background-color: rgb(51, 51, 51);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(110, 20, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(330, 10, 421, 101))
        self.lineEdit_4.setStyleSheet("background-color: rgb(179, 177, 150);\n"
"border-radius:12px;")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.frame_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "CRYPTOGRAPHY SYSTEM"))
        self.label_2.setText(_translate("Form", "Write your message here:"))
        self.label_3.setText(_translate("Form", "Write the Key :"))
        self.label_4.setText(_translate("Form", "Write E for \"Encrypt\" and D for \"Decrypt\":"))
        self.SHOW.setText(_translate("Form", "SHOW"))
        self.RESET.setText(_translate("Form", "RESET"))
        self.EXIT.setText(_translate("Form", "EXIT"))
        self.label_5.setText(_translate("Form", "The result :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
